RNIap_kotlinVersion=1.8.22
RNIap_minSdkVersion=23
RNIap_targetSdkVersion=35
RNIap_compileSdkVersion=35
RNIap_buildToolsVersion=35.0.0
RNIap_ndkversion=23.1.7779620
RNIap_playServicesVersion=18.1.0
RNIap_amazonSdkVersion=3.0.7
RNIap_playBillingSdkVersion=9.0.0
RNIap_isAmazonDrmEnabled=true

android.useAndroidX=true
android.enableJetifier=false
